### ISSUE TITLE
Wurst Crashing

### ISSUE THREAD

**Issue by TheTacticalNewb** [Wurst-Imperium/Wurst-Client-Bugs#139]
#### Description of the Bug
This was happening when I was playing with some friends. I was turning on some hacks and then my game crashed. I tried to log back in but when ever I loaded something up it crashed. Please help me with this bug.
#### How to Reproduce the Bug
I'm not sure which mod it was I think it was nuker or speed nuker with a few other mods and it will crash. 
#### Other Information
- I think you should let the players access the mods they have on from the title screen.
- Wurst Client version: 1.10x
- Operating system: Windows 10

**Comment by BoozyBazoon** [comment]
I have the same issue. After turning on a few mods like nuker and stuff it crashed.
Now every time I try to open a world it crashes because you can only access the mods in game.
Having the ability to turn them off in the title screen will probably fix this issue.

Wurst Client version: 1.10x
Operating system: Mac OS X 10.8.5

**Comment by HackerOnMineCraft** [comment]
There should be some way to edit what mods you enabled through the Wurst files, but Im not sure how.

**Comment by pvppro19** [comment]
Try reinstalling wurst
