### ISSUE TITLE
When i press left shift and click on flight/jetpack etc it is red and it wont work

### ISSUE THREAD

**Issue by P4ND4X** [Wurst-Imperium/Wurst-Client-Bugs#179]
![capture](https://cloud.githubusercontent.com/assets/20903482/17477313/797668b2-5d19-11e6-8f55-b83d3bf9ab16.PNG)

**Comment by pvppro19** [comment]
this is because you have a bypass on. in wurst 1.8,1.9, and 1.10, there is bypasses for anticheat. if a mod/hack can't bypass the anticheat plugin specified, it will block the mod/hack from being toggled. in this case, glide can't bypass whatever bypass you're using, so it will not be toggled and will show up red in the gui because of that
